#!/bin/bash

setup() {
	echo "Setup starting.."
	haspip=$(which pip3)
	if [ -z "$haspip" ]; then
		sudo apt-get install -y python3-pip
	fi
	pip3 install opencv-contrib dlib face_recognition
	cd ~/
	if [ ! -d "cams" ]; then
		git clone "https://github.com/darthmonkey2004/cams.git"
	fi
	cd cams
	./scan.networkCameras.sh
	echo "Setup exiting..."
	
		
}
camsdir="/home/monkey/.local/lib/python3.6/site-packages/cams"
if [ ! -d "$camsdir" ]; then
	setup
fi
cd "$camsdir"
if [ -n "$1" ]; then
	script="$1"
else
	script="server"
fi

isrunning=$(pgrep python3)
if [ -n "$isrunning" ]; then
	echo "Python running. Killing..."
	sudo kill $(pgrep python3)
fi
python3 $script.py& disown
sleep 5
cameras=$(python3 -c "import $script; cameras = $script.readConfToShell(); print (cameras)" | grep -v "None")
readarray cameras <<< "$cameras"
pos=0
for cam in "${cameras[@]}"; do
	pos=$(( pos + 1 ))
	cam=$(echo "$cam" | cut -d $'\n' -f 1)
	python3 -c "import $script; $script.analyze_stream($pos)"& disown
done
exit
